---
deployment:
  tasks:
    - export DEPLOYPATH=/home/exgcgcl/public_html/
    - /bin/cp -f index.html $DEPLOYPATH
    - /bin/cp -Rf assets $DEPLOYPATH
    - /bin/cp -Rf forms $DEPLOYPATH
    - /bin/cp -Rf vendor $DEPLOYPATH
    - /bin/cp -f .htaccess $DEPLOYPATH
